### ISSUE TITLE
不是最终的直链

### ISSUE THREAD

**Issue by super1207** [MHanL/LanzouAPI#2]
你好，我使用了你的接口，但是发现所获得的直链并不是最终的直链，不能用迅雷等一些下载工具直接下载，或者，在我的程序中，都是不能直接下载的。我探索出了基于你的接口来获取最终直链的办法，但是我不会php，这是额外的那部分python代码： https://paste.ubuntu.com/p/dr86Jm9DrY/
我希望你能把它转化成相应的 php代码，感谢。

**Comment by MHanL** [comment]
感谢指正，很抱歉现在才看到这条消息，已经按照你提供的建议进行了修复
