### ISSUE TITLE
发现一个特例，无法调用API下载

### ISSUE THREAD

**Issue by szkzn** [MHanL/LanzouAPI#3]
蓝奏链接：https://www.lanzous.com/i59farg
无法输出直链和直接下载，其他链接没发现问题，都能正常调用

形如
1.cn/?url=https://www.lanzous.com/i59farg&type=down
1.cn/?url=https://www.lanzous.com/i59farg
或者给文件加上密码
1.cn/?url=https://www.lanzous.com/i59farg&type=down&pwd=agwv
也是不行

**Comment by szkzn** [comment]
开发者调试工具，发现服务端返回 错误代码500

**Comment by szkzn** [comment]
github报错 “Something went really wrong, and we can’t process that file.”，无法上传图片，我把报错截图2张打包成了zip压缩包了，链接：http://mail.qq.com/cgi-bin/ftnExs_download?k=7766336117d79c9a606f095d4363504a5702565955015a071c050b03564e565707541e03070251480355015200025603055000526572620d451243b6d1afcea7da5303514b190b153110&t=exs_ftn_download&code=1f3aecbe

**Comment by MHanL** [comment]
代码更新了，我测试是可以正常获取到(更新前没测试)。
