### ISSUE TITLE
 建议把默认Ua设置为常量

### ISSUE THREAD

**Issue by lengye2014** [MHanL/LanzouAPI#7]
`define(USER_AGENT,'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36');`

**Comment by Nine55** [comment]
<br />
<b>Warning</b>:  Missing argument 2 for MloocCurlGet(), called in /www/wwwroot/47.2/index.php on line 27 and defined in <b>/www/wwwroot/47.2224/index.php</b> on line <b>161</b><br />
<br />
<b>Warning</b>:  Missing argument 2 for MloocCurlGet(), called in /www/wwwroot/47.240.37.224/index.php on line 106 and defined in <b>/www/wwwroot/47.240.37.224/index.php</b> on line <b>161</b><br />
<br />
<b>Warning</b>:  Missing argument 4 for MloocCurlPost(), called in /www/wwwroot/47.24224/index.php on line 112 and defined in <b>/www/wwwroot/47.3724/index.php</b> on line <b>180</b><br />

这是什么问题啊，能解析就是还带上这句..

**Comment by lhempire** [comment]
突然之间不能用了 麻烦看一下
<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function MloocCurlGet(), 1 passed in /index.php on line 26 and exactly 2 expected in /index.php:160
Stack trace:
#0 /index.php(26): MloocCurlGet('https://www.lan...')
#1 {main}
  thrown in <b>/index.php</b> on line <b>160</b><br />

**Comment by MHanL** [comment]
已修复
