### ISSUE TITLE
突然之间不能用了 麻烦看一下

### ISSUE THREAD

**Issue by lhempire** [MHanL/LanzouAPI#8]
<br />
<b>Fatal error</b>:  Uncaught ArgumentCountError: Too few arguments to function MloocCurlGet(), 1 passed in /index.php on line 26 and exactly 2 expected in /index.php:160
Stack trace:
#0 /index.php(26): MloocCurlGet('https://www.lan...')
#1 {main}
  thrown in <b>/index.php</b> on line <b>160</b><br />

**Comment by MHanL** [comment]
已修复
